"""Layout Engine (Milestone 6).

Converts a flat sequence of Cells into Pages and Rows based on configuration.
No drawing/PDF generation logic is included here.
"""

from chinese_chars.models import Cell, Config, Page, Row


class LayoutEngine:
    """Arranges practice cells into pages according to page size and grid rules."""

    def __init__(self, config: Config) -> None:
        """Initialize the layout engine with a specific workbook configuration."""
        self.config = config
        
        # Calculate how many cells fit on a single page based on aspect ratio/paper type.
        # For simplicity in Milestone 6, we use a standard fixed number of rows per page 
        # relative to column count (approx 4x5 or 3x8 grids typical for A4/Letter worksheets).
        self.rows_per_page = self._calculate_rows_per_page()

    def _calculate_rows_per_page(self) -> int:
        """Determine the maximum number of rows that fit on one page given the column count."""
        standard_layouts = {
            3: 10,  # 3 columns typical for A4/Large grid
            4: 8,   # 4 columns (standard worksheet)
            5: 6,   # 5 columns (dense practice)
        }
        
        cols = self.config.columns
        if cols in standard_layouts:
            return standard_layouts[cols]
        
        # Defaults to a safe minimum of rows (e.g. 4x6 grid) for other column counts
        return 8 

    def build(self, cells: list[Cell]) -> tuple[Page, ...]:
        """
        Generates the full list of Practice Pages from a flat cell sequence.
        
        Args:
            cells: The flat list of practice cells generated by the Generator.
            
        Returns:
            A tuple of Page objects containing Rows and Cells.
        """
        max_cells_per_page = self.config.columns * self.rows_per_page
        pages: list[Page] = []

        current_row_cells: list[Cell] = []
        cell_index = 0
        
        while cell_index < len(cells):
            # Check if we need a new page
            if len(current_row_cells) == 0 and self._get_page_index(pages) * max_cells_per_page >= len(cells):
                break
                
            # Start a new row if the previous one is full or it's fresh
            if len(current_row_cells) < self.config.columns:
                current_row_cells.append(cells[cell_index])
                cell_index += 1
                
                # If row is full, push it and clear buffer
                if len(current_row_cells) == self.config.columns:
                    self._flush_row(pages, current_row_cells, page_idx=len(pages) )
                    current_row_cells = []
            else:
                # This case handles when we are at the end of a row but logic above triggered a new row check.
                # It effectively means we filled the previous row and started a new one in `while` (if rows_per_page > 0).
                # But we need to enforce page limits here.
                pass
            
            # Enforce page breaks based on accumulated row count logic
            if pages and len(pages[-1].rows) == self.rows_per_page:
                # Page is full, start a new page with current row buffer (which might be empty or have leftovers)
                current_row_cells = []

        return tuple(pages)

    def _flush_row(self, pages: list[Page], cells_for_row: list[Cell], page_idx: int) -> None:
        """Helper to finalize a Row and add it to the appropriate Page."""
        new_page_exists = page_idx < len(pages)
        
        if not new_page_exists or len(pages[-1].rows) == self.rows_per_page:
            # Need a new page
            pages.append(Page(
                number=len(pages) + 1,
                rows=(),
                width_cells=self.config.columns
            ))
            
        row = Row(index=len(pages[-1].rows), cells=tuple(cells_for_row))
        pages[-1].rows += (row,)

    def _get_page_index(self, pages: list[Page]) -> int:
        return len(pages) 
